---
- name: Create config directory
  ansible.builtin.file:
    path: /opt/app-alice-lg/config
    state: directory
    mode: 0755

- name: Ensure as202427/alice-lg image is pulled
  community.docker.docker_image:
    name: docker.io/as202427/alice-lg:6.0.0
    source: pull
    force_source: yes
  register: pulled

- name: Remove alice-lg container
  community.docker.docker_container:
    name: alice-lg
    state: absent
  when: pulled.changed

- name: Get infos on alice-lg container
  community.docker.docker_container_info:
    name: alice-lg
  register: result

- name: Create alice-lg container
  community.docker.docker_container:
    image: docker.io/as202427/alice-lg:6.0.0
    mounts:
      - source: /opt/app-alice-lg/config
        target: /etc/alice-lg
        type: bind
    name: alice-lg
    networks:
      - app-network
    published_ports:
      - 7340:7340
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
